baseURL = "https://statictask.io"
title = "Statictask"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
